# Generated by Django 2.2.11 on 2020-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
