# Generated by Django 2.2.11 on 2020-05-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='Comments',
        ),
    ]
