# Generated by Django 2.2.11 on 2020-05-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200517_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
